[build]
builder = "nixpacks"

[deploy]
startCommand = "echo 'Railway deployment configured!'"
restartPolicyType = "on_failure"

[[services]]
name = "backend"
path = "backend"
envs = [
    { name = "PORT", default = "8000" }
]

[[services]]
name = "frontend"
path = "frontend"
envs = [
    { name = "PORT", default = "3000" },
    { name = "REACT_APP_API_URL", value = "${RAILWAY_DOMAIN_BACKEND || 'https://backend-production.up.railway.app'}" },
    { name = "REACT_APP_WS_URL", value = "${RAILWAY_DOMAIN_BACKEND ? 'wss://'.concat(RAILWAY_DOMAIN_BACKEND).concat('/ws') : 'wss://backend-production.up.railway.app/ws'}" }
] 